[package]
name = "nft_comments"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin_access = "2.0.0"
openzeppelin_upgrades = "2.0.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
