[package]
name = "creator_coin"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"
openzeppelin_access = "=2.0.0"
openzeppelin_introspection = "=2.0.0"
openzeppelin_token = "=2.0.0"
openzeppelin_utils = "=2.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis" }

[dev-dependencies]
snforge_std = "0.59.0"
assert_macros = "2.18.0"

[[target.starknet-contract]]
sierra = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "snforge test"
